### ISSUE TITLE
version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Moonli16Cxl6/usr/bin/../lib/libplacebo.so.349)

### ISSUE THREAD

**Issue by onlineapps-cloud** [cgutman/moonlight-qt#1421]
hi, latest version of moonlight-qt not working on my system, previous version (Moonlight-6.0.1-x86_64) work as expected.
Error log:
```
./Moonlight-6.1.0-x86_64.AppImage 
./Moonlight-6.1.0-x86_64.AppImage: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Moonli16Cxl6/usr/bin/../lib/libplacebo.so.349)
```
```
System:    Kernel: 6.0.0-6mx-amd64 [6.0.12-1~mx21+1] x86_64 bits: 64 compiler: gcc v: 10.2.1 
           parameters: BOOT_IMAGE=/vmlinuz-6.0.0-6mx-amd64 root=UUID=<filter> ro quiet splash 
           Desktop: KDE Plasma 5.20.5 tk: Qt 5.15.2 wm: kwin_x11 vt: 7 dm: LightDM 1.26.0 
           Distro: MX-21.3_KDE_x64 Wildflower January 15  2023 
           base: Debian GNU/Linux 11 (bullseye) 
```

**Comment by humdogm** [comment]
What C++ version are you running?

**Comment by Eruvae** [comment]
The same issue occurs on Ubuntu 20, which only supports up to GLIBCXX_3.4.28. It looks like the system used to compile the AppImage got updated, which means older systems are [no longer supported](https://docs.appimage.org/reference/best-practices.html#binaries-compiled-on-old-enough-base-system). You can try another release version - on Ubuntu 20, the Snap release still works. You could try Flatpak on MX Linux.

**Comment by Eruvae** [comment]
```
strings /lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
```
This command will list the GLIBCXX versions your libstdc++ is compatible with.

**Comment by humdogm** [comment]
> > What C++ version are you running?
> 
> i don't know how to check it, can you give me command to execute in terminal?

`apt list --installed | grep libstdc++`

**Comment by Eruvae** [comment]
Yeah, this is to be expected, since MX-21 is based on Debian 11 (Bullseye), which comes with GCC 10. GLIBCXX_3.4.29 is supported from GCC 11 onward. If you want to use this AppImage, you could consider [upgrading to MX-23](https://mxlinux.org/wiki/system/upgrading-from-mx-21-to-mx-23-without-reinstalling/), which is based on Debian 12 (Bookworm), and should come with GCC 12. Alternatively, you can try if one of the other releases like Flatpak works. Or you can hope that the maintainers release a version compiled on an older system. You could of course also compile it yourself.
