### ISSUE TITLE
Error spam in log while pressing mouse button down on title bar

### ISSUE THREAD

**Issue by jhakonen** [cgutman/moonlight-qt#90]
**Describe the bug**
***Windows 10***
With Moonlight in windowed mode if you press left mouse button down on top of Moonlight's title bar, the video output freezes. At same time log file fills with errors (see attached zip file). Errors end and video unfreezes when the button is released.
Can also reproduce this if you shift+right click window's button in taskbar.

Tried with three different config setups:
* With all video settings on automatic (Moonlight-1538322975.log)
* With video codec forced to H.264 (Moonlight-1538323085-force-h264.log)
* With video decoder forced to software (Moonlight-1538323217-force-software.log)

No errors in log with software decoder, but video did freeze with that one too.

***Ubuntu 18.04***
Tried with self compiled version. Couldn't reproduce, no errors in log and Moonlight's video output does not freeze.

**Moonlight settings (please complete the following information)**
No changes except those mentioned in bug's description.

**Client PC details (please complete the following information)**
 - OS: Windows 10 1803
 - Moonlight Version: v0.5.1 (portable)

**Logs (please attach)**
[x64-0.5.1-error-spam.zip](https://github.com/moonlight-stream/moonlight-qt/files/2431724/x64-0.5.1-error-spam.zip)

**Comment by cgutman** [comment]
These errors are because Windows stops presenting frames from DirectX when the window is being resized or moved. On the DXVA2 renderer, the backlog of unpresented frames causes the surface pool to run out of video output surfaces. When it does, it can't decode any more frames and you see the FFmpeg errors caused by `get_buffer()` failing.

The software decoder has the same issue but it can continue decoding because it's not using hardware surfaces. It will just consume more and more memory with decoded frames until the move/resize is completed. Once we can start drawing again, Pacer will drop the extra frames.

I don't think this is really fixable from our side. And even if it was, it's not going to be something user-visible.

**Comment by jhakonen** [comment]
Thank you for explanation. I was stumped why it was failing. I also tried googling about this but I couldn't find anything useful. Do you happen to know any (microsoft's?) documentation that would explain this case?

Since this a feature of Windows, then would it make sense to try to detect this situation and suppress those errors, as this is not an error situation?

**Comment by cgutman** [comment]
This seems to have disappeared in my refactoring of the decoder code. Interesting.
